# Generated by Django 5.2.1 on 2025-05-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('ingredients', models.TextField()),
                ('preparation_time', models.TimeField(max_length=100)),
                ('instructions', models.TextField(max_length=200)),
            ],
        ),
    ]
